<?php
require __DIR__.'/bootstrap.php';require __DIR__.'/layout.php';$u=require_login();$rows=[];$term=trim($_GET['documento']??'');
$show=static fn($value):string=>$value===null||trim((string)$value)===''?'No disponible':(string)$value;
$date=static function($value):string{if(!$value)return 'No disponible';try{return(new DateTimeImmutable((string)$value))->format('d/m/Y');}catch(Throwable){return 'No disponible';}};
if($term!==''){$q=$db->prepare("SELECT c.*,o.id operacion_id,o.cedente,o.cartera,o.numero_operacion,o.saldo,o.capital,o.fecha_castigo,d.id documento_id,d.estado documento_estado,d.solicitado_por documento_solicitado_por FROM clientes c LEFT JOIN operaciones o ON o.cliente_id=c.id LEFT JOIN documentos d ON d.operacion_id=o.id AND d.tipo='CESION_DERECHOS' WHERE c.numero_documento=? AND(o.activa_en_asignacion=1 OR o.id IS NULL)");$q->execute([$term]);$rows=$q->fetchAll();}
page_start('Buscar cliente',$u);?><section class="panel"><form method="get" class="inline"><label>DNI / Documento<input name="documento" value="<?=e($term)?>" required></label><button class="primary">Buscar</button></form></section><?php if($term!==''&&!$rows):?><div class="alert">No se encontraron resultados.</div><?php endif?><?php foreach($rows as $r):?>
<article class="panel client-result">
 <div class="client-head"><div><h2><?=e($r['nombre_completo'])?></h2><p><?=e($r['tipo_documento'])?> <?=e($r['numero_documento'])?> · <?=e($r['cedente'])?> / <?=e($r['cartera'])?> · Operación <?=e($r['numero_operacion'])?></p></div><div class="actions"><?php if($r['documento_estado']==='DISPONIBLE'):?><a class="secondary" href="<?=url('descargar-documento.php?id='.(int)$r['documento_id'])?>">Descargar Cesión de Derechos</a><?php elseif($r['cedente']==='SMA_INVERSIONES'&&$r['documento_id']):?><?php if($r['documento_estado']==='ERROR'||!$r['documento_solicitado_por']):?><form method="post" action="<?=url('solicitar-cesion.php')?>" class="cesion-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="documento_id" value="<?=(int)$r['documento_id']?>"><button class="secondary cesion-request" type="submit"><?=$r['documento_estado']==='ERROR'?'Reintentar':'Generar'?> Cesión de Derechos</button></form><?php else:?><span class="badge">Cesión solicitada</span><?php endif?><?php endif?><?php if($r['operacion_id']):?><a class="primary" href="<?=url('nuevo-acuerdo.php?operacion='.(int)$r['operacion_id'])?>">Generar acuerdo</a><?php endif?></div></div>
 <div class="financial-summary"><div><span>Deuda total</span><strong><?=money($r['saldo'])?></strong></div><div><span>Monto capital</span><strong><?=money($r['capital'])?></strong></div><div><span>Fecha de castigo</span><strong><?=e($date($r['fecha_castigo']))?></strong></div></div>
 <section class="client-profile"><div class="profile-head"><h3>Información complementaria del cliente</h3><span>Perfil enriquecido</span></div><div class="profile-grid">
  <div><span>Edad</span><strong><?=e($r['edad']===null?'No disponible':$r['edad'].' años')?></strong></div><div><span>Situación laboral</span><strong><?=e($show($r['situacion_laboral']))?></strong></div><div><span>Último sueldo</span><strong><?=$r['ultimo_sueldo']===null?'No disponible':money($r['ultimo_sueldo'])?></strong></div><div><span>RUC de trabajo</span><strong><?=e($show($r['ruc_trabajo']))?></strong></div>
  <div class="profile-wide"><span>Empresa</span><strong><?=e($show($r['empresa_trabajo']))?></strong></div><div><span>Deuda SBS</span><strong><?=$r['deuda_sbs']===null?'No disponible':money($r['deuda_sbs'])?></strong></div><div><span>Perfil SBS</span><strong><?=e($show($r['perfil_sbs']))?></strong></div><div><span>Bienes registrados</span><strong><?=e($show($r['bienes']))?></strong></div><div><span>Departamento</span><strong><?=e($show($r['departamento_perfil']))?></strong></div>
 </div></section>
</article>
<?php endforeach;page_end();
