<?php
require __DIR__.'/bootstrap.php'; require __DIR__.'/layout.php'; $u=require_login();
$opId=(int)($_GET['operacion']??$_POST['operacion_id']??0);
$q=$db->prepare('SELECT o.*,c.nombre_completo,c.numero_documento,c.telefono,c.correo,c.id cliente_id,r.descuento_maximo,r.monto_minimo,r.cuotas_maximas FROM operaciones o JOIN clientes c ON c.id=o.cliente_id LEFT JOIN campanas cp ON cp.cedente=o.cedente AND cp.cartera=o.cartera AND cp.activa=1 AND CURDATE() BETWEEN cp.fecha_inicio AND cp.fecha_fin LEFT JOIN reglas_negociacion r ON r.campana_id=cp.id AND r.tipo_acuerdo=COALESCE(?,r.tipo_acuerdo) AND r.activo=1 WHERE o.id=? LIMIT 1');
$q->execute([$_POST['tipo_acuerdo']??null,$opId]); $op=$q->fetch(); if(!$op){http_response_code(404);exit('Operación no encontrada');} $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf(); $tipo=in_array($_POST['tipo_acuerdo']??'', ['CANCELACION','CONVENIO'],true)?$_POST['tipo_acuerdo']:'';
 $montoCent=(int)round(((float)($_POST['monto_acordado']??0))*100); $inicialCent=(int)round(((float)($_POST['monto_inicial']??0))*100); $saldoCent=(int)round(((float)$op['saldo'])*100); $cuotas=(int)($_POST['numero_cuotas']??0);
 $montos=$_POST['cuota_monto']??[]; $fechas=$_POST['cuota_fecha']??[]; $cuotaRows=[]; $sum=0;
 if(count($montos)===$cuotas&&count($fechas)===$cuotas){foreach($montos as $i=>$raw){$cent=(int)round(((float)$raw)*100);$date=DateTimeImmutable::createFromFormat('Y-m-d',(string)$fechas[$i]);if($cent<=0||!$date||$date->format('Y-m-d')!==$fechas[$i]){$cuotaRows=[];break;}$sum+=$cent;$cuotaRows[]=[$date->format('Y-m-d'),$cent];}}
 $telefono=trim((string)($_POST['telefono']??''));$correo=trim((string)($_POST['correo']??'-'));$correoValido=$correo==='-'||filter_var($correo,FILTER_VALIDATE_EMAIL);
 if(!$tipo||$montoCent<=0||$montoCent>$saldoCent||$cuotas<1||$cuotas>120||$inicialCent<=0||$inicialCent>$montoCent||count($cuotaRows)!==$cuotas||$sum!==$montoCent||$cuotaRows[0][1]!==$inicialCent||$telefono===''||!$correoValido)$error='La inicial debe ser la cuota 1. El teléfono es obligatorio y el correo debe ser válido o un guion (-).';
else{try{$db->beginTransaction();$descuento=round((1-$montoCent/$saldoCent)*100,2);$outside=($op['descuento_maximo']!==null&&$descuento>(float)$op['descuento_maximo'])||($op['monto_minimo']!==null&&$montoCent<(int)round($op['monto_minimo']*100))||($op['cuotas_maximas']!==null&&$cuotas>(int)$op['cuotas_maximas']);$estado=$outside?'PENDIENTE_APROBACION':'VIGENTE';$year=date('Y');$db->prepare('INSERT INTO secuencias_acuerdo(anio,ultimo) VALUES(?,LAST_INSERT_ID(1)) ON DUPLICATE KEY UPDATE ultimo=LAST_INSERT_ID(ultimo+1)')->execute([$year]);$seq=(int)$db->query('SELECT LAST_INSERT_ID()')->fetchColumn();$code=sprintf('BKC-%s-%06d',$year,$seq);$ins=$db->prepare('INSERT INTO acuerdos(codigo_acuerdo,cliente_id,operacion_id,tipo_acuerdo,saldo_negociado,porcentaje_descuento,monto_acordado,monto_inicial,numero_cuotas,fecha_acuerdo,telefono_documento,correo_documento,estado,creado_por_id,creado_por) VALUES(?,?,?,?,?,?,?,?,?,CURDATE(),?,?,?,?,?)');$ins->execute([$code,$op['cliente_id'],$opId,$tipo,$saldoCent/100,$descuento,$montoCent/100,$inicialCent/100,$cuotas,$telefono,$correo,$estado,$u['id'],$u['username']]);$id=(int)$db->lastInsertId();$ci=$db->prepare('INSERT INTO cuotas(acuerdo_id,numero_cuota,fecha_vencimiento,monto,estado) VALUES(?,?,?,?,?)');foreach($cuotaRows as $i=>$row)$ci->execute([$id,$i+1,$row[0],$row[1]/100,'PENDIENTE']);$document=$db->prepare("INSERT INTO documentos(acuerdo_id,tipo,nombre_descarga,solicitado_por) VALUES(?,?,?,?)");$dni=preg_replace('/\D/','',$op['numero_documento']);$document->execute([$id,'ACUERDO_PAGO',"Acuerdo de pago - DNI_$dni.pdf",$u['id']]);$documentId=(int)$db->lastInsertId();audit($db,$u['id'],$u['username'],'AGREEMENT_CREATED','ACUERDO',$id,null,['codigo'=>$code,'tipo'=>$tipo,'monto'=>$montoCent/100,'estado'=>$estado]);$db->commit();try{require_once __DIR__.'/pdf-generator.php';generate_document_now($db,$config,$documentId);}catch(Throwable $pdfError){error_log('Immediate agreement PDF failed: '.$pdfError->getMessage());}header('Location: '.url('acuerdos.php'));exit;}catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log('Agreement creation failed');$error='No se pudo guardar el acuerdo.';}}
}
page_start('Generar acuerdo',$u);?><section class="panel"><h2><?=e($op['nombre_completo'])?></h2><p>Documento <?=e($op['numero_documento'])?> · Operación <?=e($op['numero_operacion'])?> · Saldo <?=money($op['saldo'])?></p><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif?><form method="post" class="form-grid" id="agreement-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="operacion_id" value="<?=$opId?>"><label>Tipo de acuerdo<select name="tipo_acuerdo" required><option value="CANCELACION">Cancelación</option><option value="CONVENIO">Convenio</option></select></label><label>Monto acordado<input id="monto-acordado" type="number" name="monto_acordado" min="0.01" max="<?=e($op['saldo'])?>" step="0.01" required></label><label>Inicial<input id="monto-inicial" type="number" name="monto_inicial" min="0.01" step="0.01" required></label><label>Número de cuotas<input id="numero-cuotas" type="number" name="numero_cuotas" min="1" max="120" value="1" required></label><label>Primera cuota<input id="fecha-primera" type="date" value="<?=date('Y-m-d')?>" required></label><label>Teléfono para documento<input name="telefono" value="<?=e($op['telefono'])?>" required></label><label>Correo para documento<input type="text" name="correo" value="<?=e($op['correo']?:'-')?>" placeholder="correo@dominio.com o -" required></label><div class="installments"><div class="installments-head"><b>Calendario de cuotas</b><button type="button" id="redistribute">Redistribuir saldo</button></div><div id="installment-rows"></div><div class="totals"><span>Monto acordado <b id="total-agreed">S/ 0.00</b></span><span>Total distribuido <b id="total-distributed">S/ 0.00</b></span><span>Diferencia <b id="total-difference">S/ 0.00</b></span></div></div><div class="rule"><b>Condiciones autorizadas</b><span>Descuento máximo: <?=e((string)($op['descuento_maximo']??'No configurado'))?>%</span><span>Cuotas máximas: <?=e((string)($op['cuotas_maximas']??'No configurado'))?></span></div><button class="primary" id="create-agreement" type="submit">Crear acuerdo</button></form></section><?php page_end();
