<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
header('Content-Type: application/json; charset=utf-8');
if ($_SERVER['REQUEST_METHOD']!=='POST') { http_response_code(405); exit(json_encode(['ok'=>false])); }
$expected=(string)($config['SYNC_TOKEN']??''); $auth=(string)($_SERVER['HTTP_AUTHORIZATION']??'');
if(strlen($expected)<32||!preg_match('/^Bearer\s+(.+)$/',$auth,$m)||!hash_equals($expected,$m[1])){http_response_code(401);exit(json_encode(['ok'=>false,'error'=>'unauthorized']));}
$input=json_decode((string)file_get_contents('php://input'),true);$assignment=(string)($input['asignacion']??'');$period=(string)($input['periodo_archivo']??'');$batch=(string)($input['batch_id']??'');$rows=$input['rows']??[];$final=!empty($input['final']);$fullSnapshot=!empty($input['full_snapshot']);
if(!in_array($assignment,['SMA_INVERSIONES','KPINVEST'],true)||!preg_match('/^\d{8}$/',$period)||!preg_match('/^[a-f0-9]{32,64}$/',$batch)||!is_array($rows)||count($rows)>250){http_response_code(422);exit(json_encode(['ok'=>false,'error'=>'invalid_payload']));}
try{
 $db->beginTransaction();
 $db->prepare("INSERT INTO sincronizaciones(asignacion,periodo_archivo,batch_id,estado) VALUES(?,?,?,'INICIADA') ON DUPLICATE KEY UPDATE batch_id=VALUES(batch_id)")->execute([$assignment,$period,$batch]);
 $client=$db->prepare("INSERT INTO clientes(tipo_documento,numero_documento,nombre_completo,telefono,correo,direccion,distrito,provincia,departamento,edad,situacion_laboral,ultimo_sueldo,ruc_trabajo,empresa_trabajo,deuda_sbs,perfil_sbs,bienes,departamento_perfil,estado,origen,synced_at) VALUES('DNI',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'ACTIVO','SYNC',NOW()) ON DUPLICATE KEY UPDATE nombre_completo=VALUES(nombre_completo),telefono=COALESCE(VALUES(telefono),telefono),correo=COALESCE(VALUES(correo),correo),direccion=VALUES(direccion),distrito=VALUES(distrito),provincia=VALUES(provincia),departamento=VALUES(departamento),edad=VALUES(edad),situacion_laboral=VALUES(situacion_laboral),ultimo_sueldo=VALUES(ultimo_sueldo),ruc_trabajo=VALUES(ruc_trabajo),empresa_trabajo=VALUES(empresa_trabajo),deuda_sbs=VALUES(deuda_sbs),perfil_sbs=VALUES(perfil_sbs),bienes=VALUES(bienes),departamento_perfil=VALUES(departamento_perfil),estado='ACTIVO',synced_at=NOW(),id=LAST_INSERT_ID(id)");
 $operation=$db->prepare("INSERT INTO operaciones(cliente_id,cedente,cartera,producto,origen_entidad,numero_operacion,saldo,capital,moneda,estado,periodo_archivo,fecha_carga_origen,fecha_castigo,activa_en_asignacion,sync_batch,synced_at) VALUES(?,?,?,?,?,?,?,?,?,'ACTIVA',?,?,?,1,?,NOW()) ON DUPLICATE KEY UPDATE cliente_id=VALUES(cliente_id),cartera=VALUES(cartera),producto=VALUES(producto),origen_entidad=VALUES(origen_entidad),saldo=VALUES(saldo),capital=VALUES(capital),moneda=VALUES(moneda),estado='ACTIVA',periodo_archivo=VALUES(periodo_archivo),fecha_carga_origen=VALUES(fecha_carga_origen),fecha_castigo=VALUES(fecha_castigo),activa_en_asignacion=1,sync_batch=VALUES(sync_batch),synced_at=NOW()");
 $received=0;
 foreach($rows as $row){
  $doc=preg_replace('/\D/','',(string)($row['documento']??''));$number=trim((string)($row['operacion']??''));if($doc===''||$number==='')continue;
  $client->execute([$doc,trim((string)($row['nombre_titular']??'')),$row['telefono']??null,$row['correo']??null,$row['direccion']??null,$row['distrito']??null,$row['provincia']??null,$row['departamento']??null,$row['edad']??null,$row['situacion_laboral']??null,$row['ultimo_sueldo']??null,$row['ruc_trabajo']??null,$row['nombre_empresa']??null,$row['deuda_sbs']??null,$row['perfil_sbs']??null,$row['bienes']??null,$row['departamento_perfil']??null]);
  $clientId=(int)$db->lastInsertId();
  $operation->execute([$clientId,$assignment,$assignment==='SMA_INVERSIONES'?'SMA':'KPINVEST',$row['producto']??null,$row['origen_entidad']??null,$number,(float)($row['deuda_total']??0),(float)($row['monto_capital']??0),substr((string)($row['moneda']??'PEN'),0,3),$period,$row['fecha_carga']??null,$row['fecha_castigo']??null,$batch]);$received++;
 }
 $db->prepare('UPDATE sincronizaciones SET filas_recibidas=filas_recibidas+? WHERE batch_id=?')->execute([$received,$batch]);if($final){if($fullSnapshot)$db->prepare("UPDATE operaciones SET activa_en_asignacion=0,estado='INACTIVA' WHERE cedente=? AND sync_batch<>?")->execute([$assignment,$batch]);$db->prepare("UPDATE sincronizaciones SET estado='COMPLETA',completed_at=NOW() WHERE batch_id=?")->execute([$batch]);}$db->commit();echo json_encode(['ok'=>true,'received'=>$received,'final'=>$final,'full_snapshot'=>$fullSnapshot]);
}catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log('Portal sync failed');http_response_code(500);echo json_encode(['ok'=>false,'error'=>'sync_failed']);}
